security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_TRANSCRIPTORES: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        cgr_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: dc=cgrbv,dc=users
                search_dn: "cn=read-only-admin,dc=cgrbv,dc=users"
                search_password: password
                default_roles: ROLE_USER
                uid_key: uid

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
            
#            http_basic_ldap:
#                service: Symfony\Component\Ldap\Ldap
#                dn_string: 'uid={username},dc=cgrbv,dc=users'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_TRANSCRIPTORES }
        - { path: ^/news/, role: ROLE_TRANSCRIPTORES }