<?php

namespace CGR\DGTI\BlogBundle\Repository;

/**
 * TipoContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContenidoRepository extends \Doctrine\ORM\EntityRepository
{
}
